export const metadata = {
  title: "verification page",
  description: "Generated by create next app",
};

export default function VerifyLayout({ children }) {
  return (
    <div className="border border-white w-[400px] h-screen rounded m-auto">
      {children}
    </div>
  );
}
